# Form implementation generated from reading ui file 'd:\Documentos\OneDrive\Renan\Engenharia Civil\Desenvolvimentos\bSDD\Source code examples\Python-Client-Console-Demo\bSDD_SimpleGUI\dialog_aboutThis.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_aboutThis_Dialog(object):
    def setupUi(self, aboutThis_Dialog):
        aboutThis_Dialog.setObjectName("aboutThis_Dialog")
        aboutThis_Dialog.resize(333, 197)
        self.verticalLayout = QtWidgets.QVBoxLayout(aboutThis_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_description = QtWidgets.QLabel(aboutThis_Dialog)
        self.label_description.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.verticalLayout.addWidget(self.label_description)

        self.retranslateUi(aboutThis_Dialog)
        QtCore.QMetaObject.connectSlotsByName(aboutThis_Dialog)

    def retranslateUi(self, aboutThis_Dialog):
        _translate = QtCore.QCoreApplication.translate
        aboutThis_Dialog.setWindowTitle(_translate("aboutThis_Dialog", "Dialog"))
        self.label_description.setText(_translate("aboutThis_Dialog", "<html><head/><body><p><span style=\" font-weight:700;\">bSDD SimpleGUI </span></p><p><span style=\" font-weight:700;\">version 18/08/2022</span></p><p><span style=\" font-weight:700;\">MIT License</span></p><p>Developed by Renan Rocha Ribeiro</p><p>Doctorate student at Doctoral Program in Civil Engineering (<span style=\" font-weight:700;\">PDEC</span>) at <span style=\" font-weight:700;\">University of Minho</span></p></body></html>"))
